# Generated by Django 4.2 on 2025-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QbixSolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('E-commerce', 'E-commerce Project'), ('Portfolio', 'Portfolio Website'), ('Business', 'Business Website'), ('SaaS', 'SaaS Platform'), ('Mobile App', 'Mobile Application'), ('Web App', 'Web Application'), ('CMS', 'CMS Website'), ('Booking', 'Booking System'), ('Education', 'Education Platform'), ('Healthcare', 'Healthcare System'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
